from django.db import models

# Create your models here.


class Player(models.Model):
    year = models.IntegerField()
    name = models.CharField(max_length=50)
    team = models.CharField(max_length=50)
    position = models.CharField(max_length=50)
    rush_attempts = models.IntegerField()
    rush_yards = models.IntegerField()
    yards_per_rush = models.FloatField()
    rush_touchdowns = models.IntegerField()
    rushes_per_touchdown = models.FloatField()
    fumbles = models.IntegerField()
    pass_attempts = models.IntegerField()
    pass_completions = models.IntegerField()
    completion_percentage = models.FloatField()
    pass_yards = models.IntegerField()
    yards_per_pass_attempt = models.FloatField()
    yards_per_completion = models.FloatField()
    pass_touchdowns = models.IntegerField()
    passes_per_touchdown = models.FloatField()
    interceptions = models.IntegerField()
    targets = models.IntegerField()
    receptions = models.IntegerField()
    catch_percentage = models.FloatField()
    receiving_yards = models.IntegerField()
    yards_per_reception = models.FloatField()
    yards_per_target = models.FloatField()
    receiving_touchdowns = models.IntegerField()
    receptions_per_touchdown = models.FloatField()
    targets_per_touchdown = models.FloatField()
    total_attempts = models.IntegerField()
    total_yards = models.IntegerField(default=0)
    yards_per_attempt = models.FloatField(default=0)
    total_touchdowns = models.IntegerField()
    attempts_per_touchdown = models.FloatField()
    games = models.IntegerField()
    attempts_per_game = models.FloatField()
    points = models.FloatField()
    points_per_game = models.FloatField()
    points_per_attempt = models.FloatField()
