# Generated by Django 3.1 on 2020-08-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='yards_per_attempt',
            field=models.FloatField(default=0),
        ),
    ]
