# Generated by Django 3.1 on 2020-08-24 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20200824_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position_rank',
        ),
    ]
