# Generated by Django 3.1 on 2020-08-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_remove_player_position_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='average_value_over_replacement',
        ),
        migrations.RemoveField(
            model_name='player',
            name='starting_value_over_replacement',
        ),
    ]
