# Generated by Django 3.1 on 2020-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20200824_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='average_replacement_over_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='starting_replacement_over_value',
            field=models.FloatField(default=0),
        ),
    ]
