# Generated by Django 3.1 on 2020-08-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20200825_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='average_replacement_over_value',
            new_name='average_value_over_replacement',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='starting_replacement_over_value',
            new_name='starting_value_over_replacement',
        ),
    ]
